import initTabNav from "./modules/tab-nav.js";
import initScrollAnimation from "./modules/scroll-animation.js";
import initScrollSmooth from "./modules/scroll-smooth.js";
import initAccordion from "./modules/accordion.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initBitcoin from "./modules/fetch-bitcoin.js";

initTabNav();
initScrollAnimation();
initScrollSmooth();
initAccordion();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initBitcoin();
